### ISSUE TITLE
My implementation is showing no divider. How can I use f.e "<" as a divider?

### ISSUE THREAD

**Issue by aFluxx** [tabuna/breadcrumbs#19]
Hello there,

This is what my front looks like:
https://i.gyazo.com/0585fdb66bbd34e79ab15ad1b5cc2a0c.png

Here's the implementation:
https://i.gyazo.com/f9ac2441d1c80220f8724b8a27550355.png

Is there a way to use "<" as a divider?

I can push it through in the routes file, but that doesn't really seem clean:
https://i.gyazo.com/54cd557edbb082536f4e46474ce3bff6.png

**Comment by tabuna** [comment]
Hey @aFluxx, It seems to be the best option to do this with CSS. For instance:

```css
.breadcrumb-item+.breadcrumb-item::before {
    display: inline-block;
    padding-right: .5rem;
    color: #6c757d;
    content: "<";
}
```

If this does not suit you for some reason, you can [use your Blade template](https://github.com/tabuna/breadcrumbs#output-the-breadcrumbs-use-blade-view).
